# Generated by Django 3.1.4 on 2020-12-19 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tblcategory',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(default='https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-image_large.png?format=jpg&quality=90&v=1530129081', upload_to='documents/')),
                ('itemname', models.CharField(max_length=50)),
                ('itemdesc', models.CharField(max_length=80)),
                ('startbiddate', models.DateTimeField()),
                ('endbiddate', models.DateTimeField()),
                ('startbidprice', models.FloatField()),
                ('status', models.IntegerField()),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.category')),
            ],
            options={
                'db_table': 'tblitem',
            },
        ),
    ]
