# Generated by Django 3.1.4 on 2020-12-19 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('currenttime', models.DateTimeField(auto_now=True)),
                ('placedbid', models.FloatField()),
                ('itemid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'db_table': 'tblbid',
            },
        ),
    ]
