# Generated by Django 3.1.4 on 2020-12-19 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='username',
        ),
        migrations.AddField(
            model_name='bid',
            name='usern',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
