# Generated by Django 3.1.4 on 2020-12-19 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_auto_20201219_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='usern',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currenttime', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.bid')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblwinners',
            },
        ),
    ]
